OnlineStore.Web/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Common.Constants;
using OnlineStore.Models.WebModels.Admin.BindingModels;
using OnlineStore.Services.Admin.Interfaces;
using System.Threading.Tasks;

namespace OnlineStore.Web.Areas.Admin.Controllers
{
    public class CategoriesController : BaseAdminController
    {
        private readonly IAdminCategoriesService adminCategoriesService;

        public CategoriesController(IAdminCategoriesService adminCategoriesService)
        {
            this.adminCategoriesService = adminCategoriesService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var models = this.adminCategoriesService.GetAllCategories();

            return View(models);
        }

        [HttpGet]
        public IActionResult CreateCategory()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory(CategoryBindingModel model)
        {
            if (ModelState.IsValid == false)
            {
                this.AddStatusMessage(ModelState);
            }
            else
            {
                await this.adminCategoriesService.CreateCategoryAsync(model);
                this.AddStatusMessage(ControllerConstats.MessageSuccefullyCreated, ControllerConstats.MessageTypeSuccess);
            }

            return Redirect("/Admin/Categories");
        }

        [HttpGet]
        public async Task<IActionResult> AddSubcategory(string categoryId)
        {
            var model = await this.adminCategoriesService.PrepareSubCategoryModelForAdding(categoryId);

            if (model == null)
            {
                this.AddStatusMessage(ControllerConstats.ErrorMessageWrongId, ControllerConstats.MessageTypeDanger);
                return RedirectToAction("Index");
            }

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddSubcategory(SubCategoryCategoryBindingModel model)
        {
            if (ModelState.IsValid == false)
            {
                this.AddStatusMessage(ModelState);
                return this.View();
            }

            await this.adminCategoriesService.AddSubcategory(model);

            this.AddStatusMessage(ControllerConstats.MessageSuccefullyAdded, ControllerConstats.MessageTypeSuccess);

            return this.RedirectToAction("Index");
        }
    }
}

OnlineStore.Web/Areas/Admin/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Services.Admin.Interfaces;
using System.Threading.Tasks;
using OnlineStore.Common.Constants;

namespace OnlineStore.Web.Areas.Admin.Controllers
{
    public class OrdersController : BaseAdminController
    {
        private readonly IAdminOrderService adminOrderService;

        public OrdersController (IAdminOrderService adminOrderService)
        {
            this.adminOrderService = adminOrderService;
        }

        public async Task<IActionResult> Index()
        {
            var models = await this.adminOrderService.GetAllOrdersAsync();

            return this.View(models);
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(string orderId)
        {
            var result = await this.adminOrderService.CancelOrderAsync(orderId);
            if (result == false)
            {
                this.AddStatusMessage(ControllerConstats.ErrorMessageWrongId, ControllerConstats.MessageTypeDanger);
            }
            else
            {
                this.AddStatusMessage(ControllerConstats.MessageStatusChangedSuccefully, ControllerConstats.MessageTypeSuccess);
            }
            
            return this.RedirectToAction("Index");
        }
    }
}

OnlineStore.Web/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Common.Constants;
using OnlineStore.Services.Admin.Interfaces;
using System.Threading.Tasks;

namespace OnlineStore.Web.Areas.Admin.Controllers
{
    public class UsersController : BaseAdminController
    {
        private readonly IAdminUsersService adminUsersService;

        public UsersController(IAdminUsersService adminUsersService)
        {
            this.adminUsersService = adminUsersService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await this.adminUsersService.PrepareModelForEditingAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeState(string userId)
        {
            var result = await this.adminUsersService.ChangeStateAsync(userId);

            if (result.Succeeded == false)
            {
                this.AddStatusMessage(result);
            }
            else
            {
                this.AddStatusMessage(ControllerConstats.MessageStatusChangedSuccefully, ControllerConstats.MessageTypeSuccess);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string userId)
        {
            var result = await this.adminUsersService.Delete(userId);

            if (result.Succeeded == false)
            {
                this.AddStatusMessage(result);
            }
            else
            {
                this.AddStatusMessage(ControllerConstats.MessageDeletedUserSuccefully, ControllerConstats.MessageTypeSuccess);
            }

            return RedirectToAction("Index");
        }
    }
}

OnlineStore.Web/Areas/Identity/Controllers/MyOrdersController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Services.UserServices.Interfaces;
using System.Threading.Tasks;

namespace OnlineStore.Web.Areas.Identity.Controllers
{
    public class MyOrdersController : BaseIdentityController
    {
        private readonly IUserMyOrdersService userMyOrdersService;

        public MyOrdersController(IUserMyOrdersService userMyOrdersService)
        {
            this.userMyOrdersService = userMyOrdersService;
        }

        public IActionResult Index()
        {
            var model = this.userMyOrdersService.PrepareIndexModelForDisplaying(this.User);

            return View(model);
        }
    }
}

OnlineStore.Web/Views/Shared/_DisplayTempData.cshtml
@if (TempData.Keys.Any(k => k.StartsWith(ControllerConstats.StatusMessagePrefix)))
{
    foreach (var key in TempData.Keys.Where(v => v.ToString().StartsWith(ControllerConstats.StatusMessagePrefix)))
    {
        <div class="alert alert-@(TempData[ControllerConstats.StatusMessageType]) alert-dismissible fade show" role="alert">
            @TempData[key]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

OnlineStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous">

    </script>
    <link href="~/css/customStyles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<body>
    <header>
        <div class="navbars-container">
            <nav class="navbar navbar-main-custom navbar-dark navbar-expand-sm">
                <div class="container-fluid navbar-main-inner">
                    <partial name="_LoginPartial" />
                </div>
            </nav>

            <nav class="navbar navbar-auxiliary-custom shadow-sm navbar-expand-sm">
                <div class="container-fluid">
                    <div class="navbar-aux-content navbar-aux-content-departments">
                        <i class="fas fa-list-ul"></i>
                        <span>Categories</span>
                        <a style="text-decoration-line: underline" href="#">
                            see all
                            <i class="fas fa-chevron-circle-right"></i>
                        </a>
                    </div>
                    <ul class="navbar-nav mr-auto collapse navbar-collapse">
                        <li class="nav-item">
                            <a class="nav-link navbar-aux-content" href="#">DAILY DEALS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Discounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Best Seller</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">New Arrivals</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link" href="#">
                                <i class="far fa-question-circle fa-lg" style="color: #005eb8"></i>
                                Info
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <partial name="_DisplayTempData">

        <div class="container-fluid">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2018 - OnlineStore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
</body>
</html>

OnlineStore.Web/Views/Shared/_LayoutAccount.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid account-container d-flex">
    <div class="account-menu">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a asp-area="Identity" asp-controller="Account" asp-action="Index">Account</a>
            </li>
            <li class="list-group-item">
                <a asp-area="Identity" asp-controller="Security" asp-action="Index">Security settings</a>
            </li>
            <li class="list-group-item">
                <a asp-area="Identity" asp-controller="MyOrders" asp-action="Index">My orders</a>
            </li>
            <li class="list-group-item">
                <a asp-page="/creditcards">My credit cards</a>
            </li>
            <li class="list-group-item">
                <a asp-page="/warranties">My warranties</a>
            </li>
            <li class="list-group-item">
                <a asp-page="/rewies">My rewies</a>
            </li>
            <li class="list-group-item">
                <a asp-page="/favorites">Favorites</a>
            </li>
        </ul>
    </div>

    <div class="account-content">
        @RenderBody()
    </div>
</div>

<script src="~/js/highlightSelectedBtn.js"></script>

@*Make li item link script*@
<script>
    $(".list-group-item").on("click", function () {
        $(this).children()[0].click();
    })
</script>

OnlineStore.Web/Views/Shared/_LayoutAdminPanel.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<div class="account-container d-flex">
    <div class="account-menu">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <a asp-area="Admin" asp-controller="Admin" asp-action="Index">Statistics</a>
            </li>
            <li class="list-group-item">
                <a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
            </li>
            <li class="list-group-item">
                <a asp-area="Admin" asp-controller="Orders" asp-action="Index">Orders</a>
            </li>
            <li class="list-group-item">
                <a asp-area="Admin" asp-controller="Categories" asp-action="Index">Categories and products</a>
            </li>
        </ul>
    </div>

    <div class="account-content">
        @RenderBody()
    </div>
</div>

<script>
    $(function () {
        let liTags = $("ul.list-group li.list-group-item");
        let urlParts = document.URL.split("/").slice(-2);

        let url = '/';

        for (let a = 0; a < urlParts.length - 1; a++) {
            url += urlParts[a] + "/";
        }

        url += urlParts[urlParts.length - 1];

        for (let a = 0; a < liTags.length; a++) {
            let hrefValue = $(liTags[a].children).attr("href");

            if (hrefValue === url) {
                $(liTags[a]).addClass("account-menu-selected");
            }
        }
    })
</script>

<script src="~/js/highlightSelectedBtn.js"></script>

<script>
    $(".list-group-item").on("click", function () {
        $(this).children()[0].click();
    })
</script>

OnlineStore.Web/Views/Shared/_ProductFormPartalView.cshtml
@model OnlineStore.Models.WebModels.Admin.BindingModels.ProductBindingModel
<form method="post" enctype="multipart/form-data">
    <input asp-for="SubCategoryId" hidden />
    <input asp-for="ProductId" hidden />
    <div class="row">
        <div class="col">
            <label asp-for="ProductName"></label>
            <input class="form-control" asp-for="ProductName" />
        </div>
        <div class="col">
            <label asp-for="CountsLeft"></label>
            <input class="form-control" asp-for="CountsLeft" />
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="Price"></label>
            <input class="form-control" asp-for="Price" />
        </div>
        <div class="col">
            <label asp-for="PromoPrice"></label>
            <input class="form-control" asp-for="PromoPrice" placeholder="0.00" />
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label asp-for="Description"></label>
            <textarea class="form-control" asp-for="Description" rows="15"></textarea>
        </div>
        <div class="col">
            <label asp-for="Specifications"></label>
            <textarea class="form-control" asp-for="Specifications" rows="15"></textarea>
        </div>
    </div>
    <div class="row">
        <label asp-for="Photos"></label>
        <input class="form-control-file" asp-for="Photos" />
    </div>

    <div class="form-group d-flex">
        <div class="mx-auto">
            <button class="btn btn-custom-border-blue" type="submit">Submit</button>
            <a asp-controller="Categories" asp-action="Index" class="btn btn-custom-border-red">Cancel</a>
        </div>
    </div>
</form>

OnlineStore.Web/Views/Shared/_ProductsPartialView.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

@model IEnumerable<ProductConciseViewModel>
@{
    ViewData["Title"] = "Products";
}
<div class="d-flex flex-row flex-wrap">
    @foreach (var productModel in Model)
    {
        <div class="product-content-inner">
            <img width="139" height="149" src="data:image/png;base64,@System.Convert.ToBase64String(@productModel.MainPhoto)" />
            <div>
                @for (int starCount = 1; starCount <= 5; starCount++)
                {
                    if (starCount > productModel.ReviewsAvgStartRating)
                    {
                        <span class="fa fa-star"></span>
                    }
                    else
                    {
                        <span class="fa fa-star star-checked"></span>
                    }
                }
                <span>@productModel.ReviewsCount reviews</span>
            </div>
            <div><strong>@productModel.Name</strong></div>
            @if (productModel.PromoPrice != null && productModel.PromoPrice > 0)
            {
                <div class="price-scrach">@productModel.Price $</div>
                <div class="price-container">@productModel.PromoPrice $</div>
            }
            else
            {
                <br />
                <div class="price-container">@productModel.Price $</div>
            }
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="row">
                    <button data-productId="@productModel.Id" class="btn btn-shoping-card">
                        <i class="fas fa-shopping-cart"></i>
                        Add to shoping card
                    </button>
                    @if (productModel.IsAddedToFavorite)
                    {
                        <button data-productId="@productModel.Id" class="btn btn-custom btn-favorite-hearth-filled">
                            <i class="fas fa-heart fa-2x ml-auto"></i>
                        </button>
                    }
                    else
                    {
                        <button data-productId="@productModel.Id" class="btn btn-custom btn-favorite-hearth">
                            <i class="fas fa-heart fa-2x ml-auto"></i>
                        </button>
                    }
                </div>
            }
        </div>
    }
</div>

@*Add product to shoping card scripts*@
<script>
    $(function () {
        let btn = $(".btn-shoping-card");

        $(btn).on("click", function (e) {
            e.preventDefault();

            let productId = $(e.currentTarget).attr("data-productId")

            $.ajax({
                url: "/ShoppingCart/AddProduct",
                method: "POST",
                data: { productId: productId }
            })
        })
    })
</script>

@*Add product to favorites scripts*@
<script>
    $(function () {
        let hearthFilledClassName = "btn-favorite-hearth-filled";
        let hearthClassName = "btn-favorite-hearth";

        let hearthFilledBtns = $("." + hearthFilledClassName);
        let hearthBtns = $("." + hearthClassName);

        $(document).on("click", "." + hearthFilledClassName, function (e) {
            let btnTarget = e.currentTarget;

            ajaxRemoveProduct(btnTarget);

            function ajaxRemoveProduct(btnTarget) {
                let productId = $(btnTarget).attr("data-productId");

                $.ajax({
                    url: "/Identity/Favorites/RemoveProduct",
                    method: "POST",
                    data: { productId: productId },
                    success: function () {
                        changeBtnClass(btnTarget, hearthFilledClassName, hearthClassName);
                    }   
                });
            }
        })

        $(document).on("click", "." + hearthClassName, function (e) {
            let btnTarget = e.currentTarget;

            ajaxAddProduct(btnTarget);

            function ajaxAddProduct(btnTarget) {
                let productId = $(btnTarget).attr("data-productId");

                $.ajax({
                    url: "/Identity/Favorites/AddProduct",
                    method: "POST",
                    data: { productId: productId },
                    success: function () {
                        changeBtnClass(btnTarget, hearthClassName, hearthFilledClassName);
                    }   
                });
            }
        })

        function changeBtnClass(btnTarget, oldClass, newClass) {
            $(btnTarget).removeClass(oldClass);
            $(btnTarget).addClass(newClass);
        }
    })
</script>